# Project 3: The Relationship between Happiness and GDP Per Capita

## Life Evaluation and Log GDP per Capita: What Drives Happiness Across Countries?
Understanding what shapes national well-being is one of the central questions in economics, psychology, and global policy research.
In this post, I explore the relationship between GDP per capita and Life Evaluation scores across countries using 2023 data.

While GDP is not a perfect proxy for quality of life, it remains one of the most widely used indicators of economic development.

In [12]:
import pandas as pd
import numpy as np
import plotly.express as px

## Exploring the Data Through Two Maps
## First Database: World Happiness Report: Life Evaluation (2023) from World Happniess Report(https://www.worldhappiness.report/)

Map 1 — Life Evaluation Scores (2023)
This map shows how people in different countries rate their overall life satisfaction. High-scoring regions include Finland, Australia, and Canada, while lower scores are concentrated in regions facing political instability or economic hardship.

In [13]:
happiness = pd.read_csv("Happiness by Country.csv")
happiness.head()

,Year,Rank,Country name,Life evaluation (3-year average),Lower whisker,Upper whisker,Explained by: Log GDP per capita,Explained by: Social support,Explained by: Healthy life expectancy,Explained by: Freedom to make life choices,...,Unnamed: 18,Unnamed: 19,Unnamed: 20,Unnamed: 21,Unnamed: 22,Unnamed: 23,Unnamed: 24,Unnamed: 25,Unnamed: 26,Unnamed: 27
0,2024.0,147.0,Afghanistan,1.364,1.301,1.427,0.649,0.0,0.155,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2023.0,143.0,Afghanistan,1.721,1.667,1.775,0.628,0.0,0.242,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2022.0,137.0,Afghanistan,1.859,1.795,1.923,0.645,0.0,0.087,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2021.0,146.0,Afghanistan,2.404,2.339,2.469,0.758,0.0,0.289,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2020.0,150.0,Afghanistan,2.523,2.449,2.596,0.370,0.0,0.126,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [14]:
# Filter the "Year" column and only keep Year == 2023
hap_2023 = happiness[happiness["Year"] == 2023][[
    "Country name",
    "Life evaluation (3-year average)"
]]

hap_2023.head()

   Country name  Life evaluation (3-year average)
1   Afghanistan                             1.721
14      Albania                             5.304
27      Algeria                             5.364
46    Argentina                             6.188
59      Armenia                             5.455

To prepare the data, I renamed the relevant columns so they match Plotly’s expected inputs:
 - Country name → Country

 - Life evaluation → LifeScore

This makes it easier to merge with other datasets later and ensures the map can correctly match country names.

In [15]:
# Rename the columns
hap_2023 = hap_2023.rename(columns={
    "Country name": "Country",
    "Life evaluation (3-year average)": "LifeScore"
})

hap_2023.head()

        Country  LifeScore
1   Afghanistan      1.721
14      Albania      5.304
27      Algeria      5.364
46    Argentina      6.188
59      Armenia      5.455

Next, I used px.choropleth() to draw a world map where each country is shaded according to its average life evaluation score in 2023. Darker colors represent higher life satisfaction.

In [16]:
# Draw the map
fig_1 = px.choropleth(
    hap_2023,
    locations = "Country",              # Country Name
    locationmode = "country names",     # Match via country names
    color = "LifeScore",                # Use color to denote the LifeScore
    color_continuous_scale = "Blues",   
    title = "World Happiness Score (Life Evaluation), 2023"
)

fig_1.show()

/var/folders/zw/2lmpwvx154x1_gp8ld2wf0_m0000gn/T/ipykernel_96067/1908818312.py:2: DeprecationWarning:

The library used by the *country names* `locationmode` option is changing in an upcoming version. Country names in existing plots may not work in the new version. To ensure consistent behavior, consider setting `locationmode` to *ISO-3*.

## Second Database: Gdp Per Capita from World Bank

Map 2 — Log GDP per Capita (2023)
This map highlights global economic differences. Wealthier regions such as North America, Western Europe, and parts of East Asia appear in darker shades, while lower-income regions remain lighter.

In [17]:
Gdp = pd.read_csv("GDP Per Capita by Country.csv")
Gdp.head()

,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,...,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024
0,Aruba,ABW,GDP per capita (current US$),NY.GDP.PCAP.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,27458.225330,27441.529660,28440.051960,30082.127640,31096.205070,22855.932320,27200.061080,30559.533530,33984.790620,NaN
1,Africa Eastern and Southern,AFE,GDP per capita (current US$),NY.GDP.PCAP.CD,186.121835,186.941781,197.402402,225.440494,208.999748,226.876513,...,1479.615260,1329.807285,1520.212231,1538.901679,1493.817938,1344.103210,1522.393346,1628.318944,1510.742951,1567.635839
2,Afghanistan,AFG,GDP per capita (current US$),NY.GDP.PCAP.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,565.569730,522.082216,525.469771,491.337221,496.602504,510.787063,356.496214,357.261153,413.757895,NaN
3,Africa Western and Central,AFW,GDP per capita (current US$),NY.GDP.PCAP.CD,121.939925,127.454189,133.827044,139.008291,148.549379,155.565216,...,1860.727694,1630.039447,1574.230560,1720.140280,1798.340685,1680.039332,1765.954788,1796.668633,1599.392983,1284.154441
4,Angola,AGO,GDP per capita (current US$),NY.GDP.PCAP.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,3213.902611,1807.952941,2437.259712,2538.591391,2189.855714,1449.922867,1925.874661,2929.694455,2309.534130,2122.083690

In [18]:
Gdp_2023 = Gdp[[
    "Country Name",
    "2023"
]]

Gdp_2023.head()

                  Country Name          2023
0                        Aruba  33984.790620
1  Africa Eastern and Southern   1510.742951
2                  Afghanistan    413.757895
3   Africa Western and Central   1599.392983
4                       Angola   2309.534130

In [19]:
# Rename the columns
Gdp_2023 = Gdp_2023.rename(columns={
    "Country Name": "Country",
    "2023": "Gdp 2023"
})
Gdp_2023["log_gdp"] = np.log10(Gdp_2023["Gdp 2023"])

Gdp_2023.head()

                       Country      Gdp 2023   log_gdp
0                        Aruba  33984.790620  4.531285
1  Africa Eastern and Southern   1510.742951  3.179191
2                  Afghanistan    413.757895  2.616746
3   Africa Western and Central   1599.392983  3.203955
4                       Angola   2309.534130  3.363524

In [20]:
# Draw the map
fig_2 = px.choropleth(
    Gdp_2023,
    locations = "Country",              # Country Name
    locationmode = "country names",     # Match via country names
    color = "log_gdp",                  # Use color to denote the log_gdp
    color_continuous_scale = "Blues",   
    title = "GDP Per Capita, 2023"
)

fig_2.show()

/var/folders/zw/2lmpwvx154x1_gp8ld2wf0_m0000gn/T/ipykernel_96067/3818259153.py:2: DeprecationWarning:

The library used by the *country names* `locationmode` option is changing in an upcoming version. Country names in existing plots may not work in the new version. To ensure consistent behavior, consider setting `locationmode` to *ISO-3*.

# Interpretation of the two maps
By comparing the two maps side by side, an intuitive pattern emerges:

Countries with higher GDP per capita tend to also report higher life evaluation scores, although there are notable exceptions.

This initial visual exploration motivated the next step—creating a scatter plot to examine the relationship more directly and quantify the trend across nations.

In [21]:
merged = pd.merge(hap_2023, Gdp_2023, on="Country", how="left")

merged.head()

       Country  LifeScore      Gdp 2023   log_gdp
0  Afghanistan      1.721    413.757895  2.616746
1      Albania      5.304   8575.171346  3.933243
2      Algeria      5.364   5364.027950  3.729491
3    Argentina      6.188  14187.482730  4.151905
4      Armenia      5.455   8125.273958  3.909838

Use Plotly to create an interactive scatter plot with a regression line:

 - Blue points represent all countries

 - The red line is the best-fit trend

 - Only the selected countries receive text labels

This keeps the figure readable while emphasizing meaningful comparisons.

Highlighting Selected Countries

 - To avoid clutter, we manually select several countries that illustrate interesting contrasts:

In [22]:
selected_countries = ["Finland", "Denmark", "United States", "China", "India", "Singapore"]

subset = merged[merged["Country"].isin(selected_countries)]

fig = px.scatter(
    merged,
    x = "log_gdp",
    y = "LifeScore",
    trendline = "ols",
    trendline_color_override = "red",
    title = "Life Evaluation vs Log GDP per Capita (2023)"
)

# Label the countries I selected
for i, row in subset.iterrows():
    fig.add_annotation(
        x = row["log_gdp"],
        y = row["LifeScore"] + 0.12,
        text = row["Country"],
        showarrow = False,
        font = dict(size = 11, color = "black")
    )

fig.show()

 # Interpreting the Relationship Between Log GDP per Capita and Life Evaluation

The scatter plot shows a clear positive relationship between a country’s economic prosperity (measured as log GDP per capita) and its average life evaluation score. As log GDP increases, countries tend to report higher levels of subjective well-being.

A few selected countries illustrate this pattern:

 - Finland and Denmark, two of the wealthiest and happiest countries, appear in the top-right corner with both high GDP and very high life evaluations.

 - The United States and Singapore also fall along the upper end of the trend, though their life evaluation scores are slightly lower than the Scandinavian countries despite comparable GDP levels.

 - China sits around the middle of the plot, reflecting its rapidly rising GDP and moderate life satisfaction.

Overall, the red trend line confirms the pattern:

Higher income levels are strongly associated with higher life satisfaction, although there is still considerable variation among countries with similar GDP levels.

This suggests that while economic development plays a major role in shaping well-being, other social, cultural, and institutional factors also matter—especially among higher-income nations where the differences in life satisfaction become more nuanced.